# Filling lists

In [ ]:
# We wish to fill a list to contain the first 100 square numbers: [0, 1, 2, 4, 9, 16, 25 ...]
# It's too long to create manually, so we want to write a loop to create the list

# Why does the following code not work?

list = []
for i in range(100) :
    list[i] = i * i
print(list)

In [ ]:
# Rewrite the above code to incrementally append each element to the list, one by one

# insert your code here


In [ ]:
# Rewrite the above code to create a list of size 100 where each element is 0

# insert  your code here


In [ ]:
# Another way of achieving the same result is as follows:

list = [0] * 100
print(list)

In [ ]:
# Rewrite your code to compute the first 100 square numbers, but this time first create a list of 100 elements that all have the value None
# And then update the elements to their correct value inside the loop

# insert your code here


In [ ]:
# Another Python mechanism for achieving the same result is as follows (using something called a list comprehension)

list = [i * i for i in range(100) ]
print(list)

In [ ]:
# Use a list comprehension to create a list of 100 numbers where each element is 0

# insert your code here


In [ ]:
# Use a list comprehension to create a list of consecutive integer numbers from 0 to 99

# insert your code here


Note: the for loop used in a list comprehension needn't be a simple range loop.

# Linear Algebra

https://en.wikipedia.org/wiki/Linear_algebra

Linear algebra requires us to represent vectors and matrices.

In this tutorial we will explore two different ways of representing Matrices in Python:
1. As a list of lists
2. As a NumPy 2-dimensional array

We will also consider two different ways of performing matrix and vector operations:
1. Using high-level NumPy functions
2. Implemented ourselves using loops that access individual elements of lists and arrays

Clearly, using high-level NumPy functions is simplier and more efficient, but there will be times when the operation we wish to perform is not available via a high-level library, so we need the programming skills to be able to implement any operation using primitive element wise operations and loops. 


# Representing Matrices as Lists of Lists

Represent the following matrices in Python code as lists of lists:

$$
a = \begin{bmatrix} 
1 & 2 & 3 \\
4 & 5 & 6 
\end{bmatrix},
b = \begin{bmatrix} 
10 & 11 & 12 \\
13 & 14 & 15 
\end{bmatrix}
$$

In [ ]:
# Insert your code here


Write a function to compute the dimensions of a matrix represented as a list of lists.

The function should return a <i>tuple</i> that contains the number of rows and number of columns.

So the above examples should return dim(a) = (2, 3)

In [ ]:
def dim(matrix) :
    # Insert your code here

In [ ]:
dim(a)

Write a function that adds together two matrices.

The result for the above two matrices should be:

$$\begin{bmatrix} 
11 & 13 & 15 \\
17 & 19 & 21 
\end{bmatrix}
$$

We already demonstrated this in the lecture examples, but try to rewrite it yourself without referring back to the lecture material.

Use the <code>dim</code> function above in your solution.

You can also assume that the two matrices provided as input have the same dimensions. You can check that by using the following Python code:

<code>assert dim(matrix_a) == dim(matrix_b)</code>

In [ ]:

def matrix_add(matrix_a, matrix_b) :
    assert dim(matrix_a) == dim(matrix_b)
    # Insert your code here

In [ ]:
matrix_add(a, b) # result should be as above

### Matrix Multiplication

To add two matrices, they need to have the same dimensions.

To multiply two matrices, the number of columns of the first matrix must be the same as the number of rows in the second matrix.

So, if the first matrix has dimension ($rowsA$, $colsA$), and the second matrix has dimension ($rowsB$, $colsB$), then $colsA$ must equal $rowsB$ and the result will have dimension ($rowsA$, $colsB$).

So let's consider a new example that has those properties:

$$
x = \begin{bmatrix} 
1 & 2 & 3 \\
4 & 5 & 6 
\end{bmatrix},
y = \begin{bmatrix} 
10 & 11 \\
12 & 13 \\
14 & 15 \\
\end{bmatrix}
$$

In [ ]:
# Represent the new matrices in Python code as lists of lists:

# insert your code here


In this case the result of multiply those two matrices will be:
$$x y = \begin{bmatrix} 
76 & 82 \\
184 & 199 \\
\end{bmatrix}
$$

Let's look at how this result is computed step by step (our algorithm will follow the same step by step proceedure).

Firstly, the value $76$ in the result matrix is computed based on the first row of matrix $x$ and the first column of matrix $y$ (highlighted in blue below):

$$x y = \begin{bmatrix} 
\color{blue}{76} & 82 \\
184 & 199 \\
\end{bmatrix}
$$

$$
x = \begin{bmatrix} 
\color{blue} 1 & \color{blue}2 & \color{blue}3 \\
4 & 5 & 6 
\end{bmatrix},
y = \begin{bmatrix} 
\color{blue}{10} & 11 \\
\color{blue}{12} & 13 \\
\color{blue}{14} & 15 \\
\end{bmatrix}
$$

- We multiply the $1$ (which is the <b>first</b> element of the first row in matrix x) by $10$ (which is the <b>first</b> element of the first column in matrix y),
we then add to that the result of 
- multiplying $2$ (which is the <b>second</b> element of the first row in matrix x) by $12$ (which is the <b>second</b> element of the first column in matrix y),
finally we add to that the result of
- multiplying  $3$ (which is the <b>third</b> element of the first row in matrix x) by $14$ (which is the <b>third</b> element of the first column in matrix y)
- to produce a grand total of $1 \times 10 + 2 \times 12 + 3 \times 14 = 76$. 

In [ ]:
#Let's start by writing Python code to compute just that first element of the result matrix

def matrix_multiply_element00(matrix_a, matrix_b) :
    # insert your code here

In [ ]:
matrix_multiply_element00(x, y) # result should be 76

Next we move on to computing the result $82$ that appears in the second column of the first row of the result matrix.
This is computed based on the first row of matrix $x$ and the <b>second</b> column of matrix $y$ (highlighted in blue below):

$$x y = \begin{bmatrix} 
{76} & \color{blue}{82} \\
184 & 199 \\
\end{bmatrix}
$$

$$
x = \begin{bmatrix} 
\color{blue} 1 & \color{blue}2 & \color{blue}3 \\
4 & 5 & 6 
\end{bmatrix},
y = \begin{bmatrix} 
{10} & \color{blue}{11} \\
{12} & \color{blue}{13} \\
{14} & \color{blue}{15} \\
\end{bmatrix}
$$
 
- We multiply the  1  (which is the first element of the first row in matrix x) by  11  (which is the first element of the second column in matrix y), we then add to that the result of
- multiplying  2  (which is the second element of the first row in matrix x) by  13  (which is the second element of the second column in matrix y), finally we add to that the result of
- multiplying  3  (which is the third element of the first row in matrix x) by  15  (which is the third element of the second column in matrix y)
- to produce a grand total of  1×11+2×13+3×15=82.

In [ ]:
# Alter your code to compute just that second element of the first row of the result matrix

def matrix_multiply_element01(matrix_a, matrix_b) :
    # insert your code here

In [ ]:
matrix_multiply_element01(x, y) # result should be 82

In [ ]:
# Now generalize your code to compute just the element at the specified row and column position of the result matrix

def matrix_multiply_element(matrix_a, matrix_b, row, col) :
    # insert your code here 

In [ ]:
matrix_multiply_element(x, y, 0, 0) # result should be 76

In [ ]:
matrix_multiply_element(x, y, 0, 1) # result should be 82

In [ ]:
matrix_multiply_element(x, y, 1, 0) # result should be 184

In [ ]:
matrix_multiply_element(x, y, 1, 1) # result should be 199

In [ ]:
# Now implement matrix multipy by calling your matrix_multiply_element function to compute each element of the result
# Hint: it will be very similar to your matrix_add function above

def matrix_multiply(matrix_a, matrix_b) :
    # insert your code here

In [ ]:
matrix_multiply(x,y) # result should be as above

In [ ]:
# Now create a new version of your function that incorporates the code from matrix_multiply_element directly into your matrix_multiply function 
# rather than calling the matrix_multiply_element function.
# Your new function should now have triply nested for loops. 

def matrix_multiply_combined(matrix_a, matrix_b) :
    # insert your code here

In [ ]:
# Test that it still produces the same answer
matrix_multiply_combined(x,y) 

In [ ]:
# Which of these two versions do you prefer? Why?

# NumPy

Next we explore using the NumPy library to represent matrices.

In [3]:
# When using the NumPy module, we can create a 2-D array of zeros as follows:
import numpy

list = numpy.zeros((10,10))
print(list)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Represent the following matrices in Python code as NumPy arrays

$$
c = \begin{bmatrix} 
1 & 2 & 3 \\
4 & 5 & 6 
\end{bmatrix},
d = \begin{bmatrix} 
10 & 11 & 12 \\
13 & 14 & 15 
\end{bmatrix}
$$

In [4]:
import numpy

# insert your code here


In [ ]:
# How do we compute the equivalent of our dim function for NumPy arrays?

# insert your code here


In [ ]:
# Add together matrix c and d using the NumPy add function

# insert your code here


In [ ]:
# Or, even more simply ...
c+d

### For matrix multiply, let's use this example:

$$
p = \begin{bmatrix} 
1 & 2 & 3 \\
4 & 5 & 6 
\end{bmatrix},
q = \begin{bmatrix} 
10 & 11 \\
12 & 13 \\
14 & 15 \\
\end{bmatrix}
$$

In [ ]:
# insert your code to create NumPy arrays here


In [ ]:
# matrix multiplication can similar be done simply using the NumPy dot function

# insert your code here


In [ ]:
# Or we could do it the hard way and compute matrix multiply ourselves element by element as we did above.
# Change your matrix_mult function so that it operates on NumPy arrays rather than lists of lists

# insert your code here
def array_multiply(array_a, array_b) :
    # insert your code here

In [ ]:
array_multiply(p, q)

In [ ]:
# What was the main difference?