# Matrix Addition
$$\left[\begin{array}{ccc}1&2&3\\ 4&5&6\\ 7&8&9\end{array}\right] + \left[\begin{array}{ccc}10&11&12\\ 13&14&15\\ 16&17&18\end{array}\right] = \left[\begin{array}{ccc}11&13&15\\ 17&19&21\\ 23&25&27\end{array}\right]$$


In [1]:
# representing matrices as lists of lists
x = [[1,2,3],
     [4,5,6],
     [7,8,9]]
y = [[10,11,12],
     [13,14,15],
     [16,17,18]]

In [2]:
# matrix addition using doubly nested loops to iterate over rows and columns respectively
def matrix_add(matrix1, matrix2) :
    result = []
    num_rows = len(matrix1)
    num_cols = len(matrix1[0])
    for row in range(num_rows) :
        new_row = []
        for col in range(num_cols) :
            new_row.append(matrix1[row][col] + matrix2[row][col])
        result.append(new_row)
    return result

In [3]:
matrix_add(x,y)

[[11, 13, 15], [17, 19, 21], [23, 25, 27]]

In [4]:
import numpy

In [5]:
# convert list of lists into a NumPy 2 dimensional array ...
X = numpy.array(x)
Y = numpy.array(y)

In [6]:
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
Y

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [8]:
# result type is no longer a list, it's an N dimensional array
type(X)

numpy.ndarray

In [9]:
# add two arrays using NumPy
numpy.add(X, Y)

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [10]:
#multiply two arrays using NumPy
numpy.dot(X, Y)

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [11]:
# access row 1 and then column 1 from that  row
X[1][1]

5

In [12]:
# or, treating it as a 2D array, provide a row and column index as a pair
X[1,1]

5

In [13]:
# accessing parts of a 2D array using slicing
X[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [14]:
# all columns of rows 1 to 3
X[1:3,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [15]:
# all columns of row 2
X[2,:]

array([7, 8, 9])

In [16]:
# all rows of column 2
X[:, 2]

array([3, 6, 9])

In [17]:
X[1:3,0]

array([4, 7])

In [18]:
# create a new 2D array by switching the rows columns
numpy.transpose(X)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [19]:
# create a 5 x 10 array where all values are zero
numpy.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
z = numpy.zeros((5,10))

In [21]:
# update one of the zero values to 45
z[2,2] = 45

In [22]:
z

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., 45.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [23]:
# or create an array where all values are one
numpy.ones((5,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [24]:
# a 1 dimensional array of ones
numpy.ones((5))

array([1., 1., 1., 1., 1.])

In [25]:
# a 3 dimensional array of ones
numpy.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])